import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container: {
        backgroundColor: "#1d1813",
        width: "100%",
        height: "100%",
        position: "relative",
    },
    header: {
        marginTop: 70,
        height: 40,
        width: "100%",
        //backgroundColor: "red",
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingLeft: 20,
        paddingRight: 20,
    },
    nameHome: {
        alignItems: "center",
        fontSize: 28,
        fontWeight: "bold",
        color: "#dcd3d1",
        marginLeft: 20,
    },
    ringNumber: {
        position: "absolute",
        right: 24,
        top: 14,
        zIndex: 1,
    },
    ringNum: {
        color: "#ab9570",
    },
    headerIconLeft: {
        marginTop: -20,
    },
    headerIconRight: {
        marginTop: -20,
        marginRight: 20,
    },
    line: {
        paddingTop: 10,
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        fontWeight: 400,
    },
    inline: {
        color: "#dcd3d1",
    },
    hello: {
        display: "flex",
        flexDirection: "row",
        paddingTop: 14,
        paddingLeft: 20,
    },
    helloText: {
        fontSize: 18,
        color: "#dcd3d1",
        marginLeft: 26,
    },
    helloHeart: {},
    introduceHome: {
        width: "100% - 40px",
        height: 86,
        borderRadius: 20,
        marginLeft: 20,
        marginRight: 20,
        marginTop: 20,
        borderColor: "#dbbf98",
        borderWidth: 1,
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        padding: 10,
    },
    introduceHomeimg: {
        width: 60,
        height: 60,
        borderColor: "#dbbf98",
        borderWidth: 2,
        backgroundColor: "transparent",
        borderStyle: "dashed",
        padding: 10,
        borderRadius: 30,
    },
    introduceHomeText: {
        paddingRight: 120,
    },
    introduceHomeTextMain: {
        color: "#dcd3d1",
    },
    introduceHomeTextNote: {
        color: "#dcd3d1",
    },
    introduceHomeIcon: {
        marginRight: 35,
        marginBottom: 24,
    },
    introduceHomeInIcon: {},
    utilities: {
        // width: "100% - 60px",
        // backgroundColor: "red",
        height: 400,
        marginLeft: 20,
        marginRight: 20,
        marginTop: 20,
    },
    utilitiesTow: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginTop: 20,
        width: "100%",
    },
    utilitiesChild: {
        backgroundColor: "#201e20",
        width: "48%",
        height: 80,
        borderRadius: 20,
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        borderColor: "#705235",
        borderWidth: 1,
    },
    utilitiesIcon: {
        width: 38,
        height: 38,
        marginLeft: 40,
        padding: 2,
        backgroundColor: "#403b3e",
    },
    utilitiesText: {
        marginLeft: 54,
        fontSize: 16,
        color: "#dedbde",
    },
    bottom: {
        width: "100%",
        height: 44,
        backgroundColor: "#403b3e",
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        // alignItems: "center",
        paddingTop: 10,
        position: "absolute",
        bottom: 0,
        paddingLeft: 20,
    },
    bottomIcon: {
        width: "25%",
    },
    bottomIconChild: {
        marginLeft: 54,
        height: 36,
        width: 64,
        backgroundColor: "#1d1813",
        borderRadius: 20,
    },

    btnPressedOpacity: {
        opacity: 0.5,
    },
});
